### ISSUE TITLE
[feature request] Dark mode

### ISSUE THREAD

**Issue by jamiew0w** [git-noter/gitnoter#58]
Hello!

It would be great if we could have an option for dark mode, preferably a permanent option/setting rather than a toggle (but that part is my own preference). 

Thanks!

**Comment by vivekweb2013** [comment]
Thanks @src-hyc for implementing this feature.  I've merged the PR and changes are live. I've tested it by enabling dark scheme using chrome's developer console as mentioned in this [SO Post](https://stackoverflow.com/a/59223868/814548)

Your changes are fine. It just that we will need to change some of the inline stylings to allow visibility of mui components in the dark mode. For example - the note text from the cards needs to changed to more contrast color for better visibility. Also the input components from the editor view are blended and not clearly visible.

We will need to update the inline styling of these components in a way that will work for both light and dark color scheme.
So I'm keeping this issue open for now. @src-hyc if you are interested you can create a separate PR for these styling fixes, if not I'll push the fix in my free time.

Thanks again for your contribution to the codebase.

**Comment by src-hyc** [comment]
Hello @vivekweb2013, thanks for your feedback! I'm quite interested in fixing the issue, but I don't think the website is working right now: it keeps asking me to login, and doesn't show me the page to control notes. I tried self-hosting too, and the website was keeping loading after I clicked the login button. It would be much easier for me to fix the issue if I can view the website.

I also had a view of the code, it seems that the issue is caused by the Markdown editor in [components/NoteCard.tsx](https://github.com/git-noter/gitnoter/commit/c45020877568d4cff3561ffb713391cbc63db749/src/components/NoteCard.tsx) doesn't work with `ThemeProvider`.

**Comment by vivekweb2013** [comment]
@src-hyc Are you using incognito mode in chrome? If yes please do not use the incognito mode. Also make sure that the browser is not blocking third party cookies since they are used for authentication

<img width="282" alt="image" src="https://user-images.githubusercontent.com/7036736/172039429-f48b80c0-0b2f-4c9c-87bb-6d541147e924.png">

Let me know if you still getting the issue.

**Comment by src-hyc** [comment]
Hello @vivekweb2013, yes, I was using private mode (Safari version incognito mode). I switched to the normal mode but still having the issue.

<img width="1264" alt="Screen Shot 2022-06-05 at 2 06 21" src="https://user-images.githubusercontent.com/100218098/172039630-e6cdb8ac-5d3c-4b9a-9a65-a2d80c6c79f5.png">

It seems to be related to CORS, and we may need to open another issue in the backend repo for it.

**Comment by vivekweb2013** [comment]
@src-hyc oh I see. I think there is some issue with safari. I'm investigating it. Meanwhile  could you please try chrome. Its working on chrome.

BTW those errors issues are not the problem. Since they are only related to the youtube video.

**Comment by src-hyc** [comment]
So according to #66, can this issue be closed right now? @vivekweb2013

**Comment by vivekweb2013** [comment]
yes. closing this
